name: Auto Update

on:
  schedule:
    # Run daily at midnight UTC
    - cron: "0 0 * * *"
  workflow_dispatch: # Allows manual triggering
  push:
    branches:
      - main

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Skip if Commit is from GitHub Actions
        run: |
          if [[ "$(git log -1 --pretty=format:'%an')" == "github-actions[bot]" ]]; then
            echo "Commit made by GitHub Actions. Skipping workflow."
            exit 0
          fi

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.x

      - name: Install Dependencies
        run: pip install jinja2

      - name: Generate README.md
        run: python update.py

      - name: Commit and Push Changes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add README.md
          git commit -m "Update README.md with current date: $(date)" || echo "No changes to commit"
          git push origin HEAD
